version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    projects:
      - name: "Jobs"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    projects:
      - name: "Jobs"
